"""drop ix_timeentry_user_start_time

Revision ID: 027de17852fc
Revises: 08cf47a8c1fa
Create Date: 2026-06-02 10:13:41.871666

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "027de17852fc"
down_revision: Union[str, Sequence[str], None] = "08cf47a8c1fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timeentry_user_start_time"), table_name="timeentry")
    op.create_index(
        "ix_timeentry_user_id", "timeentry", ["user_id", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_timeentry_user_id", table_name="timeentry")
    op.create_index(
        op.f("ix_timeentry_user_start_time"),
        "timeentry",
        ["user_id", "start_time"],
        unique=False,
    )
    # ### end Alembic commands ###
