"""add_unique_running_entry_constraint

Revision ID: 109c9b22bd5a
Revises: 027de17852fc
Create Date: 2026-06-08 18:42:41.731217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "109c9b22bd5a"
down_revision: Union[str, Sequence[str], None] = "027de17852fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_running_entry_per_user",
        "timeentry",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("end_time IS NULL"),
        sqlite_where=sa.text("end_time IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_running_entry_per_user",
        table_name="timeentry",
        postgresql_where=sa.text("end_time IS NULL"),
        sqlite_where=sa.text("end_time IS NULL"),
    )
    # ### end Alembic commands ###
